### ISSUE TITLE
Remove default host of localhost

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#105]
Request::new can be called with something that's not a URL, e.g. `/path`, and it will automatically prepend `http://localhost/`. I think that's the wrong thing in most cases. We should instead make it an error to construct a Request with a string that doesn't parse as a URL.

This will probably break a lot of doctests, but I think we should update the doctests to use real URLs. For now those can be `http://localhost/`; when #82 is fixed, those can be `http://example.com/`, with an override to point `example.com` to `localhost` so the tests run quickly and don't hit the network.

**Comment by algesten** [comment]
This comes from that early ureq API was modelled on [superagent](http://visionmedia.github.io/superagent/), which is still my goto nodejs http client and somewhat of a hero for me in API design.

> I think that's the wrong thing in most cases.

Is it? If we ask "what could the user possibly mean with this input?" 

Philosophically both ureq (and now hreq), were and are driven by a feeling that in the rust community, sometimes correctness and strict adherence to spec overrides usability concerns in API design. The [http crate](https://crates.io/crates/http) is better now, but the correctness of [hyper](https://crates.io/crates/hyper), where the http crate started, often shows in the API the user is exposed to.

> A __fast__ and __correct__ HTTP implementation for Rust.

For example [this method signature](https://docs.rs/hreq/0.3.0/hreq/trait.RequestExt.html#tymethod.header):

```rust
impl Request {
  fn header(&self, key: &str) -> Option<&str> { … }
}
```

is no good if the overriding concern for the API is correctness. Not all correct header values can be represented as rust `String`, which forces the use of `Result` and/or an intermediary [`HeaderValue`](https://docs.rs/hyper/0.13.6/hyper/header/struct.HeaderValue.html#method.to_str).

But how often do we really encounter such headers in the wild?

I want ureq (and hreq) to be correct and on spec, I want to be able to handle such headers if I find them, but without forcing the user of the API to jump through hoops. Simple, rememberable and _User first API_ (how I encapsulated these thoughts in a design goal). 

This is the bigger picture of the absence of `Result`, the synthetic http error, and why using a path as URL defaults to localhost.

In early ureq I did however lurch too far in the other direction, so in the same way I'm for reintroducing some `Result` instead of synthetic http error, also the localhost-by-default decision is up for challenge.

**Comment by jsha** [comment]
Thanks for the additional background on the API design!

I think we can probably find a middle path, where we keep the API simple and also filter out some error cases, by deferring all errors until `.do_call()`. We would accept any String in the constructor of Request, and do validation later. If `.do_call()` finds that the URL is invalid, it would return a Response with the `Error` field already set.
