### ISSUE TITLE
Late TLS errors break agent pooling

### ISSUE THREAD

**Issue by algesten** [algesten/ureq#124]
When using an agent pooled connection, we try to validate the connection before use, but some TLS errors might surface as late as when we start reading the response. 

https://github.com/algesten/ureq/blob/master/src/unit.rs#L172

```rust
body::send_body(body, unit.is_chunked, &mut stream)?;

// start reading the response to process cookies and redirects.
let mut stream = stream::DeadlineStream::new(stream, unit.deadline);let mut resp = Response::from_read(&mut stream);
```

In practice the error could probably surface already on `send_body`, however it's hard to detect the error once the body is sent.

The solution might be to buffer something like 2kb of the body, send it, try to read response headers but look out for `WouldBlock` – a TLS error would probably surface here.

The mechanic of reading response headers before sending entire body is necessary anyway to properly handle 307 `Expect: 100-Continue`, so this bug and that feature should be thought of in tandem.

See background here #122

**Comment by jsha** [comment]
> The solution might be to buffer something like 2kb of the body, send it, try to read response headers but look out for WouldBlock – a TLS error would probably surface here.

How about another approach - we can make `unit.rs` aware of Payload. So e.g. unit::connect would take a Payload argument instead of a Reader. Most Payloads (Empty, Text, JSON, Bytes) are replayable; only Reader is not. So we could have more generic logic that says "if we get a connection-related error during a request-response cycle, and HTTP semantics say the request is retryable, we will retry it." With the exception that Payload::Reader is never retryable once it's started being read. Users who want retryability would have to use one of the replayable body types.

**Comment by algesten** [comment]
@jsha 

> Most Payloads (Empty, Text, JSON, Bytes) are replayable; only Reader is not.

Yeah, that's way simpler. I'm just thinking of my own use case for work with ureq. I stream large bodies (video files). It's unfortunate if it behaves differently depending on type of body.
