### ISSUE TITLE
Error should be cloneable

### ISSUE THREAD

**Issue by sergiimk** [algesten/ureq#126]
Hi, I was giving this library a try but found error handling extremely painful.

I'd like to be able to compose errors (for example re-emit `ureq::Error::ConnectionFailed` as `myapp::Error::ResourceUnavailable`) while preserving the original error as `source` not to lose any detailed information for debugging.

Library currently prevents any composition because `ureq::Error` does not implement `Clone` and `Response.synthetic_error()` returns `&Option<Error>`. This means I can inspect the error but neither move it out of the response nor clone it.

Any attempt to box it via `Box::new(e)` or `e.into()` results in rather confusing error message:
```
Box::new(e)
^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `&ureq::error::Error`
```

I'd also recommend taking a look at `thiserror` crate as it can fill some gaps in your `Error` implementation (e.g. providing `Error.source()` for `Io(IoError)`) while maintaining backwards compatibility.

**Comment by jsha** [comment]
Thanks for the report! As a quick fix, what do you think of adding `impl std::error::Error for &Error {}` in addition to the current `impl std::error::Error for Error {}`? I thnk that would allow a boxed `ureq::Error` to serve as a source.

**Comment by BurntSushi** [comment]
I don't think implementing `std::error::Error` for `&Error` would help much here, because it would imply returning a borrowed error as a source and `source` has a `'static` bound. I do think that enabling composition is pretty important. I think you have a few choices available to you to do this:

* Make your error type cloneable. (This may be difficult if your error type embeds an `io::Error`.)
* Provide an `into_synthetic_error` API that consumes the response and returns a `Result<Response, Error>`, where the return value is the response itself if there is no error and the error itself otherwise.
* Provide some kind of mutable API that permits one to extract an error out of a response if it exists. e.g., I think `&mut Option<ureq::Error>` would do the trick, because then callers could use [`Option::take`](https://doc.rust-lang.org/std/option/enum.Option.html#method.take) to transfer ownership. However, this is a bit unwieldy, and it's not clear what role a response that errored but has no error would play.
* My guess is that #128 would also somewhat provide a way out of this, but it would be a little weird to require the use of a convenience API just to enable error composition.

Personally, I think an `into_synthetic_error` is probably the best option here.

**Comment by algesten** [comment]
@BurntSushi 

I agree `into_synthetic_error` sounds like the best option. I've also seen other crates have an explicit `Error::into_io_error -> Option<io::Error>`, which we could consider.

**Comment by mmstick** [comment]
Hit this same problem. I need to use this in a function that returns one of multiple kinds of errors, but that's not possible to return an error by reference.

**Comment by jsha** [comment]
Hi @mmstick ! Thanks for the report, it's really useful to hear from folks with this problem. Would you mind checking out https://github.com/algesten/ureq/pull/132 and building against it to see if it would solve your problem? We're making changes to the API for a 2.0.0 release to solve this and other problems, so we'd like to make sure it provides a solution before finalizing the API.
