### ISSUE TITLE
set_tls_config should be on Agent

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#159]
Right now we have `Request.set_tls_config`. I believe this should `Agent.set_tls_config` instead, because TLS settings concern the establishment of connections, and connections are managed by Agent rather than Request. As a concrete example, someone could create an Agent, make one request for `example.com` with a TLS config containing a client certificate, then make another request with a different TLS config not containing the client certificate (that is, removing authentication from the second request). The result would be unpredictable: If a connection got reused, the request would be made on a connection that had a client certificate. But if a new connection was made, the request would be made on a connection without a client certificate.

I propose we add the setting to Agent and deprecate (but not remove) the setting on Request. When we move to 2.0.0 we could actually remove the setting on Request.

**Comment by algesten** [comment]
I agree that TLS config belongs on `Agent`, but I think it's also valid on `Request` for the cases where you use an implicit agent. As such I wouldn't want to deprecate on Request, but I totally see your example case for pooling and how this becomes an issue.

One idea would be to keep the TLS config in use for a pooled connection and only reuse a connection if it's the exact same config. Sadly [rustls::ClientConfig](https://docs.rs/rustls/0.18.0/rustls/struct.ClientConfig.html) doesn't implement `PartialEq`, so we can't use equivalence.

Since we use the config in an `Arc` I'm wondering if we can compare pointer addresses?

**Comment by jsha** [comment]
Done in `release-2.0`.
