### ISSUE TITLE
Use domain from Cookie itself

### ISSUE THREAD

**Issue by algesten** [algesten/ureq#209]
A concern for 2.0. This signature feels a bit redundant to me.

```rust
    pub fn set_cookie(&self, cookie: Cookie<'static>, url: &Url) {
```

Cookie has a `domain` value, which means the `url: &Url` is effectively doubling up something internal to Cookie.If we start relying on the internal `domain`, we can make the function easier to use. We just need to decide what happens if there is no domain set? I would assume, ignore the cookie, alternatively error at request time.

**Comment by jsha** [comment]
The domain on the cookie actually has different semantics than the domain in the URL. For instance, if I POST `https://login.example.com/login`, it can return a `Set-Cookie` header for `example.com` (parent domain), which will successfully set a cookie at the higher level domain, and that cookie would be sent to all subdomains of `example.com`. If it returned a `Set-Cookie` header for `blah.login.example.com` (subdomain), the cookie would be ignored. If it returned a `Set-Cookie` header with no Domain field, that would mean "send this cookie to `login.example.com` but not any subdomains."

https://tools.ietf.org/html/rfc6265#section-5.3

In theory, since the user is calling `set_cookie`, we could trust them to set the `Domain` field to the domain they want the cookie stored on instead of the `Domain` field parsed out of the cookie header. But this would not allow the user to specify the "host only" behavior I described for when the domain is empty. It would also be risky, since a user that naively parsed a Set-Cookie header without checking it against the request host would allow `evil.com` to set cookies for `example.com`.

**Comment by algesten** [comment]
I am convinced. I'd like to remove `set_cookie` altogether. See notes in #203
