### ISSUE TITLE
Chose error style

### ISSUE THREAD

**Issue by algesten** [algesten/ureq#262]
#255, #256 and #257 have three different styles for errors. We need to pick one.

Personally I'm leaning towards #257. Other thoughts?

**Comment by jsha** [comment]
I'm leaning towards #255 (in the modified version where `into_response` returns Result). The thing I dislike about #257 is that it locks us into a specific representation for Response-based errors. If we wanted to add some new field to `Error` that would be relevant for both `Status` and `Transport` errors, we couldn't add it to the enum without seriously breaking compatibility.

Based on your enthusiasm for it, though, I'll give it a deeper look. Maybe the restriction I describe above isn't such a big restriction after all. In one way of looking at it, the concept of a status error is that the user would have otherwise gotten a Response, but we just wrapped it in an Error so they can easily use `?`. So we wouldn't actually expect to want to change representations in the future.

**Comment by algesten** [comment]
What about non-exhaustive on the enum? Does that alleviate your concern?

**Comment by jsha** [comment]
Non-exhaustive on the enum doesn't really address my concern. I'm not worried that we would want to add a third variant, I'm worried that we would want to add some new field that applies to both variants (say, `timestamp` as an arbitrary example). Still, that's not the end of the world - we could add `timestamp` to both Response and Transport. After thinking about it some more I'm liking #257 too. In particular I figured out a fairly nice and simple approach to matching that's demonstrated in the doctest:

```rust
use std::{result::Result, time::Duration, thread};
use ureq::{Response, Error, Error::Status};
# fn main(){ ureq::is_test(true); get_response( "http://httpbin.org/status/500" ); }

// An example of a function that handles HTTP 429 and 500 errors differently
// than other errors. They get retried after a suitable delay, up to 4 times.
fn get_response(url: &str) -> Result<Response, Error> {
    for _ in 1..4 {
        match ureq::get(url).call() {
            Err(Status(503, r)) | Err(Status(429, r)) => {
                let retry: Option<u64> = r.header("retry-after").and_then(|h| h.parse().ok());
                let retry = retry.unwrap_or(5);
                eprintln!("{} for {}, retry in {}", r.status(), r.get_url(), retry);
                thread::sleep(Duration::from_secs(retry));
            }
            result => return result,
        };
    }
    // Ran out of retries; try one last time and return whatever result we get.
    ureq::get(url).call()
}
```

Previously, I had stripped out just the error for matching like so:

```
let err: ureq::Error = match result {
    Ok(r) => return Ok(r),
    Err(e) => e,
};
```

Which added extra complexity. But by importing `Error::Status`, it becomes reasonably concise to match both the `Err` and the `Status` in one clause, and return the rest immediately.

@jyn514, does #257 meet your needs? And what are your thoughts on the style?

**Comment by jyn514** [comment]
You went with https://github.com/algesten/ureq/pull/257 :) so I think this can be closed.
