### ISSUE TITLE
ureq::Error is massive

### ISSUE THREAD

**Issue by Nemo157** [algesten/ureq#296]
```rust
[src/main.rs:17] std::mem::size_of::<ureq::Error>() = 576
```

It would be nice if this wasn't so large so that users don't need to `Box` it to avoid copying around a lot of unused memory in cases like `Result<(), ureq::Error>::Ok(())`.

Unfortunately, the size seems to mostly come from `Response`, and it's publicly visible that `ureq::Error::Http` contains a `Response`-by-value, so I don't know any way to non-breakingly fix this other than boxing `Response`'s data internally, which would affect performance on the success path too.

```
[src/main.rs:18] std::mem::size_of::<ureq::Response>() = 432
[src/main.rs:19] std::mem::size_of::<ureq::Transport>() = 568
```

**Comment by jsha** [comment]
Good point, thanks for raising it. That's a bummer that we're somewhat painted into a corner by the design of `ureq::Error::Status` (BTW I'm assuming you're talking about the `Status` variant; there's no `Http` variant in 2.0.0). Of course, we could always take another major revision and go to 3.0.0. Doing so shortly after the release would minimize the pain of people upgrading twice.

I'd be interested in digging into `Response` to see if we can reduce its size in general.

Do you happen to have any benchmarks that could show us the performance penalty of the large Error object?

**Comment by Nemo157** [comment]
https://github.com/serde-rs/json/issues/184 is the only benchmarking I've seen, supposedly a 5% performance improvement dropping `serde_json::Error` from 56 to 8 bytes.

**Comment by jyn514** [comment]
Another alternative is to make `Response` smaller instead of boxing it. The only things I see that could be big are `Option<Url>`, `ResponseStatusIndex`, `Option<Unit>`, or `Stream`. It would be nice to narrow down which are making it so big.

**Comment by algesten** [comment]
Some investigation. This is compiling on an M1 mac which I suspect is the reason my numbers are different.

Since `Transport` contains `Response`, the two enum error variants are quite similar.

```
ureq::Error 984
ureq::Transport 976
ureq::Response 840
```

In `Response` these are the top offenders.

```
Response::url 88
Response::stream 496
Response::unit 176
```

`Stream` is another enum (for TLS vs plain):

```
TcpStream 4
rustls::StreamOwned 456
```

So 46% of `Error` size is from rustls. This reminds me that I had seen this size difference before (clippy warning about big enum size difference), but for fear of performance, opted for keeping as is rather than tucking it away on the heap.

However that fear might be misguided. The relative time taken by syscalls and network access are likely to be the true bottlenecks rather than dereferencing a reference to a stream.

Without too crazy changes in Resonse, I can `Box` both `Unit` and `Stream`. This reduces the `Error` size to 328. Does that sound like enough improvement and does anyone see a problem with accessing Stream and Unit through boxes?

**Comment by jyn514** [comment]
Stream is private - could you box the rustls stream instead of the whole enum?

I agree the performance different for boxing it is probably negligible compared to making network requests.

**Comment by algesten** [comment]
Sure I can box just rustls stream. What difference would it make to do that versus the whole enum?

**Comment by jyn514** [comment]
It means that checking the enum discriminant doesn't have to do a pointer dereference, and means anything else using `Stream` internally also benefits from the size reduction.

**Comment by algesten** [comment]
Ah, yes! @jyn514 do you think I should bother boxing unit too? I'm not really sure what size `Error` would be acceptable.

**Comment by jyn514** [comment]
I think you should ask @Nemo157 about that :laughing:

**Comment by jsha** [comment]
Rather than boxing `Response.unit`, we should get rid of it. It's only used in one place, `Response::into_reader`, to determine if the request was a `HEAD`. That, in turn, is used to build a `LimitedRead` of 0. When we implement https://github.com/algesten/ureq/issues/264, a Response to a HEAD request will have a zero-length Vec body, and so `Response::into_reader` won't need to know it was a HEAD.

Boxing rustls::StreamOwned: I think that's definitely reasonable, particularly given that it's private to the implementation. It also makes sense conceptually - the stream's lifetime is longer than any Response that uses it, and ownership of the stream is handed back and forth between ConnectionPool and Response. However, I'm wary of making performance-motivated changes without a benchmark. As discussed in this thread, we could wind up harming performance instead of helping it; we could wind up performance neutral; or we could wind up improving performance, only for it to backslide later without us noticing.

I think we should make this change if (a) we write a benchmark showing it's an improvement, or (b) if we find documentation or a blog post specific to the Rust compiler saying, e.g. "for values that are passed on the stack, it's generally worthwhile to box anything above X bytes."

**Comment by algesten** [comment]
I think this is fixed now. Reopen if it needs to be further handled.

**Comment by edmorley** [comment]
Hi :-)

It looks like the size of `ureq::Error` increased between 2.3.1 and 2.4.0, Clippy on our CI is now failing with:

```
error: large size difference between variants
  --> examples/example-02-ruby-sample/src/util.rs:26:5
   |
26 |     RequestError(ureq::Error),
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ this variant is 224 bytes
   |
   = note: `-D clippy::large-enum-variant` implied by `-D warnings`
note: and the second-largest variant is 16 bytes:
  --> examples/example-02-ruby-sample/src/util.rs:27:5
   |
27 |     CouldNotCreateDestinationFile(std::io::Error),
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant
help: consider boxing the large fields to reduce the total size of the enum
   |
26 |     RequestError(Box<ureq::Error>),
   |                  ~~~~~~~~~~~~~~~~

error: large size difference between variants
```
(https://github.com/Malax/libcnb.rs/runs/4720581020?check_suite_focus=true)

We'll resolve this by boxing for now, but mentioning in case this increase was not expected.

**Comment by algesten** [comment]
Good observation thanks!

I think I'll make some test for this to keep it in check.

**Comment by algesten** [comment]
@edmorley Running 2.3.1 vs 2.4.0. On my machine (macbook m1):

`cargo test --all-features ensure_error_size -- --nocapture`

* 2.3.1 Error size: 208
* 2.4.0 Error size: 224

The test will scream if this goes over 500 (it used to be >900). I think the bigger question is. How big is too big?

**Comment by homeworkprod** [comment]
> I think the bigger question is. How big is too big?

Cannot answer that, but at least Clippy on Rust 1.69.0 warns me about it being "at least 240 bytes":
```
warning: the `Err`-variant returned from this function is very large
  --> src/api.rs:14:6
   |
14 | ) -> Result<ureq::Response, ureq::Error> {
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `Err`-variant is at least 240 bytes
   |
   = help: try reducing the size of `ureq::Error`, for example by boxing large elements or replacing it with `Box<ureq::Error>`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err
```
