### ISSUE TITLE
Request::get_method, get_url gone in v2

### ISSUE THREAD

**Issue by tl-alex-butler** [algesten/ureq#297]
I was using these for terse logging of my test requests & responses, e.g.
```rust
eprintln!("-> {} {}", req.get_method(), req.get_url());
```
So I could build the `Request`s normally in many places and have a single place I logged the request & response info. 

I could use the `Debug` impl of `Request` but it includes, in my case, lots of auth header noise that i didn't want. So it would be nice to have a way to access the `Request` method & url again.

**Comment by algesten** [comment]
Hi! This is somewhat related to #295 – i.e. helper methods to simply inspect the state of Request and Response.

I think it's worth considering putting some of this back. What do you think @jsha ?

**Comment by jsha** [comment]
I'm open to bringing these back. Some thoughts on why I wanted to remove them: Request is a builder object, and in some sense write-only. That doesn't have to be the case, of course, but it's a nice abstraction. For one thing, it means user code is less likely to use an in-progress `Request` as an in/out param rather than purely an out param; the former pattern often leads to code that is hard to reason about, in my opinion.

 It feels like accessor methods for fields belong more on the built request object. But we currently don't expose that built object (we call it Unit internally).
 
 A couple of ideas for this specific use case:
 
  - We recently added support for the `log` crate, and we log requests and responses.
  - We should add a `Display` impl for Request that is much shorter than our `Debug` impl.

@tl-alex-butler, do either of those approaches work well for you?
  
Also, we should tweak the Debug impl so known sensitive headers, like `Authorization` and `Cookie`, are omitted. That helps prevent accidental storage of credentials in logs.

**Comment by tl-alex-butler** [comment]
Thanks for the replies. For my use case having a `Display` impl: `ureq::get("https://example.com"` -> `GET https://example.com` would work well.

It also makes at least some sense, as method & path are the two keys parts of a `Request`.

**Comment by lolgesten** [comment]
I've found additional reason to bring these back. I use these methods to provide AWS request signing. It's currently impossible to inspect the "state" of the request to calculate the signature headers to add.

**Comment by jsha** [comment]
That makes sense. Let's bring them back!

**Comment by algesten** [comment]
PR is open.
