### ISSUE TITLE
feature: Custom connect function, like AgentBuilder.resolver

### ISSUE THREAD

**Issue by tv42** [algesten/ureq#301]
Hi. I have a low-level concern where I want to perform setsockopt calls between socket and ~bind~connect syscalls, specifically `SO_MARK`. Would you be open to a pull request that adds an AgentBuilder.connect or some such method, that takes something like say

```
pub trait Connector: Send + Sync {
    pub fn connect(&self, addrs: Vec<SocketAddr>, timeout: Option<Duration>) -> IoResult<TcpStream>;
}
```

Feedback would be most welcome. I think I can write the code pretty easily, but wanted to reach out first.

**Comment by tv42** [comment]
Also, is there a better type than `TcpStream`? Consider in-memory test implementations, UNIX domain sockets (`curl --unix-socket`), etc. All I could quickly find was https://crates.io/crates/multisock , is there no `Stream` in `std`?

**Comment by jsha** [comment]
I think the overall idea sounds good. I'll have to think a little on the exact API. Do we want to take a `Vec<SocketAddr>` and let the connector decide about retries / internally? Or take a `SocketAddr` and have `ureq` do retries? I think `Vec<SocketAddr>` is probably right.

I think this trait should probably take a deadline rather than a timeout, since that's what ureq is using internally. Otherwise ureq would need to transform from a deadline back to a timeout.

> Also, is there a better type than TcpStream?

It would be nice to be more generic. For instance, rustls::StreamOwned only requires Read + Write: https://docs.rs/rustls/0.19.0/rustls/struct.StreamOwned.html. But we have some internal stuff that depends on `TcpStream` to set and clear timeouts. I don't think we can be generic and still have the ability to call those (unless we get into dynamic dispatch).

**Comment by algesten** [comment]
The dream would be to be generic over Read/Write. I wonder if this proposed `Connector ` trait could be expanded so that also our internal configurations can be dealt with using an internal implementation of the trait.

Something like a `configure()` (or possibly even more functions) that we use from selected places where we need to delegate the handling of the underlying socket.

```
pub trait Connector: Send + Sync {
    pub fn connect(&self, addrs: Vec<SocketAddr>, deadline: Option<Instant>) -> io::Result<Box<io::Read + io::Write>>;
  pub fn configure(&self, socket: Box<io::Read + io::Write>, deadline: Option<Instant>) -> io::Result<()>;
}

**Comment by tv42** [comment]
I've just discovered that I can create a new `netns` and use that to everything I needed, without needing specific support from this or any other library (as long as I stay in that special thread). Both operations need the same capability, and while the `netns` way is more complex, this program is doing netlink things anyway, so it's not a huge extra burden here.

I don't think I'm going to personally write this code, then. Thanks for your time, and for maintaining a simple, approachable, HTTP client!

**Comment by strohel** [comment]
@algesten would you be interested if we ([tonari](https://github.com/orgs/tonarino/people)) tried to contribute support for what has been mentioned in this issue?

A need emerged for us to talk to an HTTP server that is listening on UNIX domain socket (something that only [Isahc currently supports](https://docs.rs/isahc/latest/isahc/config/trait.Configurable.html#method.dial)). [`multisock`](https://crates.io/crates/multisock) has been mentioned previously and should work, but perhaps it would be more in scope for `ureq` to instead allow callers to supply their own implementation?

CC @bschwind @PabloMansanet.

**Comment by algesten** [comment]
@strohel Sure, give it a go!

I haven't thought through the consequences and what changes are required. But pretty much the only constraint is that we're keen to not have to bump the major version due to API breakage. Try and see where it goes!
