### ISSUE TITLE
"Network Error: stream did not contain valid UTF-8" error, even with 'charset' enabled

### ISSUE THREAD

**Issue by Shnatsel** [algesten/ureq#320]
On some websites, e.g. paneliste.com, ureq fails with the following error:

> Network Error: stream did not contain valid UTF-8

despite the `charset` feature being enabled.

Firefox and curl work fine.

There's 96 such websites in the top million (I'm using [Tranco list generated on the 3rd of February](https://tranco-list.eu/list/3G6L)).

Archive with all occurrences: [ureq-did-not-contain-valid-utf8.tar.gz](https://github.com/algesten/ureq/files/5983425/ureq-did-not-contain-valid-utf8.tar.gz)

Code used for testing: https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/f206362f2e81521bbefb84007cdd25242f6db590/ureq-smoke-test/src/main.rs

**Comment by algesten** [comment]
The problem with paneliste.com is that they are sending non-visible ascii as reason phrase.

`curl -L --trace x.log -H http://www.paneliste.com/`

```
0000: 48 54 54 50 2f 31 2e 31 20 33 30 32 20 44 e9 70 HTTP/1.1 302 D.p
0010: 6c 61 63 e9 20 54 65 6d 70 6f 72 61 69 72 65 6d lac. Temporairem
0020: 65 6e 74 0d 0a                                  ent..
```

`e9` here in "Déplacé Temporairement" is not us ascii. The spec says:

```
reason-phrase  = *( HTAB / SP / VCHAR / obs-text )
```

This case fits in "obs-text", which is obsolete text and is any char in the range 0x80 to 0xFF (i.e. above us-ascii, but used in iso-8859-1 etc). The recommendation is that user agents don't try to parse this.

For ureq the problem [lies here](https://github.com/algesten/ureq/blob/c833acfe5cd8e6f6bb01bde4ca71681873e8bdf9/src/response.rs#L533), we use a std rust readline which assumes utf-8.

Handling `obs-text` might be out of scope for ureq. I don't want to compromise our user friendly (`&str` based) API for reading header values. It be possible to have complementary `header_raw` calls that returns the uninterpreted bytes, but I'm not feeling particularly motivated to work on that. Would be open for someone else doing it.

I'm providing a PR that would let this site load in ureq, but would mangle any character that is in the 0x80 and above range. It relies on `from_utf8_lossy` instead of requiring strict utf8.

@jsha any thoughts on this?

**Comment by jsha** [comment]
I agree the spec allows arbitrary non-ASCII non-UTF-8 bytes in reason-phrase and in header field values (though this was surprising to me!). I think it would be okay to handle the reason phrase with `from_utf8_lossy` (since UAs aren't supposed to parse it, and it doesn't usually have semantic meaning). I am somewhat against using `from_utf8_lossy` on header field values. Vulnerabilities often arise when two systems try to clean up or canonicalize inputs, but in subtly different ways. See, for instance, request splitting and request smuggling.

It would be slightly messy to do from_utf8_lossy for reason phrase and not for header fields. Given the number of sites affected is 96 out of 1 million, I'm inclined to not fix this (with the consideration that if someone comes along and says this is blocking their work, we would reconsider).

One small thing we might want to improve: we could map_err to give more context, so instead of "stream did not contain valid UTF-8" we could say "status line contained bytes that are invalid UTF-8" or "header contained bytes that ...".

**Comment by algesten** [comment]
@jsha I agree with what you're saying. I've changed the PR to instead provide better context for errors when reading.

**Comment by kl** [comment]
I'm running in to this as well with this: https://www.fastcompany.com/90601037/american-surviellance-state-facial-recognition-hypocrisy

Any chance of getting this fixed somehow? This is a blocker for me and I would rather not have to switch to another library if possible.

**Comment by kl** [comment]
I have the following:

```rust
let agent = AgentBuilder::new().timeout(Duration::from_secs(20)).build();
let resp = agent.get(link).call().context("failed to get article")?;
let doc = Document::from_read(resp.into_reader())?;

but the result from call() is Err so I'm getting this error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Transport(Transport { kind: Io, message: None, url: Some(Url { scheme: "https", username: "", password: None, host: Some(Domain("www.fastcompany.com")), port: None, path: "/90601037/american-surviellance-state-facial-recognition-hypocrisy", query: None, fragment: None }), source: Some(Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }), response: None })', src/resolve.rs:47:39
```
So this is on the line before resp.into_reader().
