### ISSUE TITLE
2.0: Restore per request timeouts or allow Agent to re-configure timeouts?

### ISSUE THREAD

**Issue by DoumanAsh** [algesten/ureq#334]
Subj.
I would like to have option to dynamically change timeouts in my application.
With current approach I would need to re-create the whole agent from a scratch each time timeout is changed. (it is not desirable since `Agent` is field in my case)
I would prefer to have option to change it also in Agent or override in requests?

Let me know which is works for you @algesten

**Comment by jsha** [comment]
I think for a per-request timeout it's better to configure it in Request than in Agent, because if you configure it in Agent you'll have a race condition where other threads might be trying to set a different timeout.

I would support adding a `.timeout()` to Request. I think we should leave the more complex settings `connect_timeout`, `read_timeout`, and `write_timeout` as Agent-only configs.

**Comment by DoumanAsh** [comment]
Well, timeouts are just integers hence you could just make it atomic.
But per request timeouts also work for me so I'll make PR with that idea

**Comment by DoumanAsh** [comment]
On side note I wanted to have clarification about `connect_timeout` in 2.x
Overall `timeout` is supposed to take precedence over `timeout_connect` but actually it is revers https://github.com/algesten/ureq/blob/main/src/stream.rs#L368

There it checks presence of `timeout_connect` first without checking whether overall request timeout was specified (which is taken from config's `timeout` if any)
Is it a mistake?

**Comment by algesten** [comment]
@DoumanAsh 

> Is it a mistake?

It's not a mistake, if you look at the agent doc it's mentioned a couple of times. However the exact reason for it being this way eludes me right now :)

```
    /// This takes precedence over `.timeout_read()` and `.timeout_write()`, but
    /// not `.timeout_connect()`.
```

Thanks for the PR. I'm looking at it now.

**Comment by jsha** [comment]
>    /// This takes precedence over `.timeout_read()` and `.timeout_write()`, but
>    /// not `.timeout_connect()`.

I think this is what happened:

When I first wrote the "overall timeout" code, I was assuming we'd get rid of `timeout_read()` and `timeout_write()`, so rather than doing logic to allow nesting the timeouts, I just treated `timeout()` as anI think  override. I was later convinced that it's sometimes useful to have all three, but I didn't update these assumptions. We could in theory nest `timeout_read()` and `timeout_write` so on any given read/write we apply whichever is shorter: the timeout_read/write or the overall timeout.
