### ISSUE TITLE
Change per-request timeout to so it can only shorten Agent's timeout

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#339]
In https://github.com/algesten/ureq/pull/335 we introduced a per-request timeout that overrides the Agent's timeout. I'd like to propose a slight tweak to the semantics: The per-request config should only be able to make the timeout shorter, not longer. For instance, if I set `Agent.timeout` to 60s, and `Request.timeout` to 120s, the actual timeout would be 60s. But if I set `Request.timeout` to 30s, the actual timeout would be 30s.

My reasoning is that people will often want to construct a single Agent for the whole program, with default settings like max timeout. If would be confusing to find that some requests take longer than the globally configured Agent is supposed to allow.

Related: #335. /cc @DoumanAsh

**Comment by DoumanAsh** [comment]
Hm, I do not believe this would be a right approach.
The problem is that current agent is not very convenient when you need to dynamically adjust timeout.
Not to mention it will be probably error prone for users themself, because it is highly likely that they are going to miss or forget about this complication.

Well, for my use case, as we cannot re-configure client conveniently, we're not going to set agent's timeout so I do not have strong feeling as we can upgrade to 2.x anyway.
But I feel this tweak is not really beneficial. 

> If would be confusing to find that some requests take longer than the globally configured Agent is supposed to allow.

I don't really think so.
The intention is to provide override after all.
It would be weird to be allowed override only up to agent's timeout.
In that case agent's config would be better named as `max_timeout`

**Comment by jsha** [comment]
Can you tell me more about when you need to dynamically adjust timeout? It sounds as if, for your use case, it's better to not set any timeout on the Agent (effectively, an infinite timeout), and only set per-Request timeouts. Does that work for you?

**Comment by DoumanAsh** [comment]
Well yeah, that's probably what I'm going to do.
We have timeout as part of configuration, and I don't want it to be left without ability to be changed at runtime

**Comment by algesten** [comment]
@jsha I'm leaning towards letting the `Request` both extend or shorten the timeout. We can only speculate about how this will be used, is it more common to do as you say, set a max in the agent, or could it be as common to set a default in the agent that is sometimes extended?

Clamping a max on both agent and request level is easy for ureq's users to code, however if we disallow extending, the users are left stranded if they want to extend beyond the agent's max. Hence, I'm leaning towards not interfering, let the users do what they want.

**Comment by jsha** [comment]
Sounds good. A concrete use case where it's useful for a per-request timeout to extend: Imagine you have an API where most requests are short, but some requests are long (e.g. uploads). You would want to share one Agent for all requests, and set a short default timeout, but set a longer timeout for the requests you know will be longer.
