### ISSUE TITLE
Can we run agents in threads to support concurrent requests?

### ISSUE THREAD

**Issue by Sibz** [algesten/ureq#352]
I have a really straight forward use case for http requests so this library meets that need. And I figured I could have three threads servicing requests to the same host to increase through-put. However I am not seeing this and I suspect the host is limiting the throughput on their end, though they state up to 30 requests per second is fine, but I only get 3.

I am just checking that by having three threads each with there own agent, I am actually making concurrent requests, or does this library still funnel to a single requesting thread and process them one by one?

**Comment by algesten** [comment]
Each agent is completely independent and is only responsible for the requests spawned using that agent. An instance of an agent manages a pool of socket connections to a server. There's a default limit on how many connections per host the agent will pool, but you can [increase it with an agent builder](https://docs.rs/ureq/2.0.2/ureq/struct.AgentBuilder.html#method.max_idle_connections_per_host).

However, in your described scenario, I'm not sure you're hitting any limit. If the host is limiting to 30 per second and you see 3 per second, that sounds more like the limiting factor is the speed of the host serving the request (or alternatively the network between you and that host).

Since ureq is blocking/non-async, with 3 threads, you can concurrently issue 3 requests. One request would in sequence do: 

1. DNS lookup
2. Open socket 
3. TLS negotiation(?),
4. Send request
5. Wait for server to handle request
6. Receive response

If any part of this chain is slow, your throughput will suffer, and the most likely part to be slow is 5. The agent pooling will ensure step 1-3 is skipped if there already is a ready connection. Since you are using one agent per thread, the default limit of 1 connection per host is fine.

To rig a test to maximize throughput I'd do the following (just writing from memory, could be some mistake). 

```rust
const CONCURRENT: usize = 10;

let agent = ureq::builder().max_idle_connections_per_host(CONCURRENT).build();

let mut handles = vec![];

for _ in 0..CONCURRENT {
  let req = agent::get("https://my-host/blah");

  let handle = std::thread::spawn(move || {
    let resp = req.call().unwrap();
    // do something with response
  });

  handles.push(handle);
}

// wait for all requests to complete
for handle in handles {
  handle.join();
}
```

**Comment by Sibz** [comment]
Thank you very much for the detailed response. I have had the logging turned on and can see the pooling is working on each thread and it is step 5 taking it's time. I think I've triggered an undocumented rate limiting flag for this API I am using caused by the types of tests I have  been running.

**Comment by algesten** [comment]
Cool!

Maybe I should clarify, my example above reuses one Agent for multiple Requests each running in a separate thread. 

So in addition to each Agent being independent, each Request from the same Agent is also completely independent. They only share the pooling which doesn't constrain anything. If we left the connections per host setting to 1 and spawn 10 from the same Agent. We still run all 10 in parallel, however we'd incur the 1-3 steps in 9 out of 10.
