### ISSUE TITLE
Sending prelude has to perfom flush?

### ISSUE THREAD

**Issue by DoumanAsh** [algesten/ureq#361]
This is a bit of bug/question report

It seems in our code we have situations where writing prelude gets buffered without actually sending data.
For some reason it leads to sudden connection abort

Here is line in question
https://github.com/algesten/ureq/blob/main/src/unit.rs#L410

Should we always flush it? My colleague told me that flush fixes the issue for us as server no longer aborts connection

P.s. problem seems to be with re-used connections though

**Comment by jsha** [comment]
Could you provide a minimized example that reproduces this behavior? Does it reproduce against a publicly-available server?

**Comment by DoumanAsh** [comment]
Unfortunately it is not so easy, I was trying to make some simplified example, but wasn't able to achieve it.
I'll continue doing, other than that we're planning to monitor situation with PR that created to see if flush indeed fixed our problem

**Comment by DoumanAsh** [comment]
The only thing I can think of is that we may need flush in case of TLS connection as it might needs to finish writing data:
https://github.com/ctz/rustls/blob/main/rustls/src/stream.rs#L98

For regular TCP it makes no sense to flush though

**Comment by jsha** [comment]
The behavior you describe is a bit surprising to me, since I would expect it to be a problem all the time, rather than just in certain situations. And the rustls code tries to complete the underlying I/O on every write: https://github.com/ctz/rustls/blob/311c8e4fdc61c606c479d499d195089d9cac1206/rustls/src/stream.rs#L73-L76.

Can you describe a bit more about the conditions under which this triggers? Are you sending lots of headers? Large client bodies? Is there a long time between requests?

What output do you if you include env_logger and set RUST_LOG=ureq=trace,rustls=trace?

**Comment by DoumanAsh** [comment]
Unfortunately it happens quite randomly so I'm not sure right now what could be a trigger.
The request itself is quite simple POST with a bit of JSON and small amount of necessary headers(content-type/authorization).
But it is quite possible for these requests to be infrequent and have quite big gap in between (depends on user activity).

Just a note it started to appear only when we tried to re-use connections (before we didn't actually use `Agent`)

**Comment by jsha** [comment]
What's the full error message you get?

**Comment by DoumanAsh** [comment]
ureq returns `HttpRequestError("Network Error: Unexpected EOF") }`

**Comment by DoumanAsh** [comment]
@jsha Do you think it would be possible to extend retry logic to cover requests with bodies? (i.e. allow to retry if connection from pool has been aborted even if it has body)

**Comment by jsha** [comment]
> Now I think about it: ureq cannot retry once request is sent, hence re-using connections can be harmful too...

Yep, this is an issue, and I suspect it is related to https://github.com/algesten/ureq/issues/124 (where we also discussed retries with bodies).

I'd still like to dig into the exact sequence of calls that's happening differently when you flush vs not. My understanding of rustls so far was that it would try to write to the socket as part of our `write()` call, which would make this flush redundant. If that's wrong, I want to make sure I understand it correctly.

**Comment by DoumanAsh** [comment]
Yeah I get that.
Unfortunately we never encountered such issue outside of production, and even there it doesn't happen every so often.
So for now we just just disabled connection pooling to avoid this problem.

Unfortunately I'm not familiar with rustls code too.
But from what I remember when reading tokio-rustls code, it is necessary to call `flush` to guarantee that all data has been sent, this is still doesn't guarantee that none data is written at all ofc. So to perfectly sure I would need to review rustls code which is not a trivial task.

In any event I'll try to report back if I'll have some concrete evidence on why `flush` might be helping

**Comment by DoumanAsh** [comment]
I read some background on #124 and it seems the only real way to fix it is to detect connection drop early on (especially because technically you're not supposed to retry something like POST regardless of error).
If we can detect error during writing request, then we can be at least sure that request hasn't been sent or at least not completely.
As far as I know flush should complete TLS handshake at least, hence if connect was reset before we should fail because server already closed socket ( in our case server has nginx in front so we do not really connect directly to our servers when doing requests).
But other than that I have feeling we shouldn't change retry logic when fail happens after reading response.
So it is either find way to detect broken connection early (flush could be one way in case of TLS) or just to not using connection pool for Agent

**Comment by jsha** [comment]
I did some testing and I think I have a clearer idea of the problem here. When we pull a connection from the pool, we try to determine if the server closed the connection while waiting in the pool (`server_closed`). We do that by peeking on the stream; if we get a WouldBlock, we're good to go. If there are bytes on the stream, we currently (wrongly) treat that as good to go. There shouldn't be bytes on the stream until after we've made a request.

What's happening here is that the server has sent a close_notify alert, cleanly shutting down the connection. So when we do a peek, we don't get WouldBlock, we see bytes available.

I think the right thing here is to call complete_io on the stream _before_ server_closed, and if that results in a closed connection, we throw it away and create a new one. One tricky piece here is that we need to make sure to set the timeout / deadline on the stream first.

Then, after complete_io is closed, we should treat any bytes returned from a peek on the underlying stream as an error.
There's also the qu

**Comment by DoumanAsh** [comment]
Hmm while I do not see particular problem with such I approach, but I think approaching it with attempting to send prelude and flush would be more appropriate as this situation is rather an edge case so it would be better to be more optimistic and attempt to use connection immediately to send prelude and detect if it failed with flush.
This way at least we'll definitely see any error, if there to be in rare case, otherwise just proceed as normal with writing body.

I would trust your judgement here as what is important is that we make sure such errors wouldn't prevent us from using connection pooling completely as it probably unusable with TLS due to possibility of EOF error when reading response

**Comment by jsha** [comment]
@DoumanAsh I think #372 solves this. I'll work on unittests later this weekend.

**Comment by DoumanAsh** [comment]
@jsha Thanks! It does make sense to approach it this way.
Would it be ok to backport it to 1.5 branch once tests are ready?

**Comment by jsha** [comment]
I think a backport to 1.5 makes sense since this is a significant bug. Would you be willing to provide a PR for the backport?

**Comment by jsha** [comment]
2.1.1 and 1.5.5 are released with the fix.

**Comment by DoumanAsh** [comment]
Thank you
