### ISSUE TITLE
Request and Response are not very caching-friendly

### ISSUE THREAD

**Issue by jpochyla** [algesten/ureq#363]
Hi! While trying to implement caching of `ureq` responses I've noticed that the above structs could make it a bit easier:

- `Request` does not expose `url` and `method`. This would be nice for other middleware as well, but I wanted to derive the cache key from them.
- `Response` has only a constructor with a `str` argument for tests, not `Vec<u8>`, and getting the complete HTTP response bytes is also not possible.

Would you be interested in a draft PR adding these?

**Comment by jsha** [comment]
As of 2.1.0, `Request` does expose `url`, `request_url`, and `method`: https://docs.rs/ureq/2.1.0/ureq/struct.Request.html.

Having a way to build a `Response` for use in a caching layer is a good idea. I think it would be best to offer something structure, like "build a `Response` that has these headers and these bytes as a body," rather than "build a response from these exact bytes that were received as part of an HTTP response."

**Comment by algesten** [comment]
This should be solved in ureq 3.x since it's based on the http crate.
