### ISSUE TITLE
Specify minimum TLS version

### ISSUE THREAD

**Issue by insanitybit** [algesten/ureq#480]
Something nice from reqwest is the ability to specify a minimum tls version:
https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.min_tls_version:

An option for specifying the minimum version would be great.

**Comment by algesten** [comment]
Hi @insanitybit, welcome to ureq! 

Since we try to be agnostic over [TLS connector](https://docs.rs/ureq/2.4.0/ureq/struct.AgentBuilder.html#method.tls_connector)  – the question is how this API should look. It probably means we need to pass the TLS [version here](https://docs.rs/ureq/2.4.0/ureq/trait.TlsConnector.html#tymethod.connect) and then implement it differently depending on actual TLS implementation.

Whilst I'm not totally against it, I think we need to gather up these kinds of issues for a version 3.0.

However adding such a method to `AgentBuilder` is merely a convenience, since it is possible to specify TLS version by digging deeper into rustls (or native-tls), to configure this. Ureq allows setting the entire [rustls configuration object](https://docs.rs/ureq/2.4.0/ureq/struct.AgentBuilder.html#method.tls_config), which means it's possible to [configure version](https://docs.rs/rustls/0.20.2/rustls/struct.ConfigBuilder.html#method.with_protocol_versions). The equivalent API exists for native-tls too.

What we could do meanwhile is provide additional `example` cases that shows how to configure the TLS version using the current API.

**Comment by insanitybit** [comment]
> What we could do meanwhile is provide additional example cases that shows how to configure the TLS version using the current API.

That would be awesome and I think sufficient for my use case and the majority of others.
