### ISSUE TITLE
AddrInUse advice

### ISSUE THREAD

**Issue by CKingX** [algesten/ureq#523]
Hi

I need to download from a large range of URLs (over 1 million). So, to help with this, I was using rayon to help download in parallel. This worked perfectly fine in Ubuntu (I didn't go over the entire 1 million, but it managed to output 3 GB of data before I stopped it). On Windows, however, it gave this error after around 10,000 URLs accessed
```
request = Err(
    Transport(
        Transport {
            kind: ConnectionFailed,
            message: Some(
                "Connect error",
            ),
            url: Some(
                Url {
                    scheme: "https",
                    cannot_be_a_base: false,
                    username: "",
                    password: None,
                    host: Some(
                        Domain(
                            "api.pwnedpasswords.com",
                        ),
                    ),
                    port: None,
                    path: "/range/4033C",
                    query: None,
                    fragment: None,
                },
            ),
            source: Some(
                Os {
                    code: 10048,
                    kind: AddrInUse,
                    message: "Only one usage of each socket address (protocol/network address/port) is normally permitted.",
                },
            ),
        },
    ),
```
I later read up on it and the main thing here is Windows only allows up to 5000 ephemeral ports. So I updated my code to use an Agent (as it uses a connection pool that it reuses according to documentation) and send a reference (&agent) to the loop in rayon, and it still ends up with the error. Is there something I am missing? (It seems to me that it is probably my approach to this that is wrong rather than a bug in ureq)

**Comment by jsha** [comment]
Are these URLs all on the same remote IP address? If so, you'll need to limit the parallelism of your fetcher to account for the limited number of ephemeral ports. That will also provide better connection reuse (since you're using an agent).

I recommend adding a parameter to configure parallelism and starting with 1, then cranking it up to 2, etc. and see where you run into trouble, and where performance drops off. I would expect the sweet spot to be somewhere around 10-20 depending on the characteristics of your bandwidth and the remote server.

**Comment by CKingX** [comment]
Yes, it is to the same domain (so likely same IP address). Thanks! I will change the thread count of rayon.

**Comment by CKingX** [comment]
I was able to download all of it by changing the maximum number of rayon threads to 6. Thanks!
