### ISSUE TITLE
Integration with google oss-fuzz fuzzing service

### ISSUE THREAD

**Issue by manunio** [algesten/ureq#539]
Hi, I would like to help integrate this project into [OSS-Fuzz](https://github.com/google/oss-fuzz).

- As an initial step for integration I have created this PR: https://github.com/google/oss-fuzz/pull/8373, it contains necessary logic from an OSS-Fuzz perspective to integrate Ureq, This includes developing initial fuzzers as well as integrating into OSS-Fuzz.

- Essentially, OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects.

- If you would like to integrate, could I please have an email(s), it must be associated with a google account like gmail ([why?](https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication)). by doing that, the provided email(s) will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats.

- Notice the email(s) affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by jsha** [comment]
Hi @manunio! Thanks for working on this. Looking at https://github.com/google/oss-fuzz/pull/8373, it appears your fuzz target fetches an arbitrary URL with arbitrary headers. My understanding is that a good fuzz target shouldn't make network requests because (a) that makes them hard to reproduce, (b) that slows them way down, and (c) that potentially generates a lot of junk network traffic (though since most arbitrary URLs won't parse, that's not really an issue).

I think a more useful fuzzer would generate arbitrary HTTP responses and ask ureq to parse them. Any crash parsing one of those responses would be considered a bug. There may be other areas of ureq that are also good fuzz targets (for instance cookie parsing, or parsing of other specific headers like Content-Length or Transfer-Encoding).

If you decide to pursue this further, I'm happy to provide an email.

**Comment by jsha** [comment]
Hi @manunio! Thanks for the ping.

I still think your pull request to oss-fuzz has a problem: it is trying to make a "real" network request. You pointed out that `h2` appears to do the same thing, but on closer inspection, it actually mocks out the network I/O:

https://github.com/hyperium/h2/blob/756e2524ac53c0cf9810efcba0b92171b7d80e42/fuzz/fuzz_targets/fuzz_client.rs#L18-L20

The next step here is to improve the fuzz target so it doesn't do any real network I/O. One approach would be to mock out the I/O. For instance you might be able to do this with the ReadWrite trait we already have.

Another approach would be to change what you target for your first fuzzing integration. For instance, perhaps instead you would like to generate arbitrary response bodies and pass them through our parser? That way you avoid any network I/O.

**Comment by algesten** [comment]
Closing since we're moving to ureq 3.x. In 3.x the transport can be completely replaced. The mocking should be trivial.
