### ISSUE TITLE
Is it possible to "stream" a POST request?

### ISSUE THREAD

**Issue by 12932** [algesten/ureq#552]
I would like to keep track of the progress of a POST request using .send() , i'm currently using send_byes() like so:

```
	let agent = Agent::new();

	let mut byte_vector_to_send = vec![0; byte_count as usize];
	let resp = agent.post(UPLOAD_URL)
		.set("Content-Type", "text/plain;charset=UTF-8")
		.set("User-Agent", OUR_USER_AGENT)
		.send_bytes(byte_vector_to_send.as_mut_slice())?;

	
	// read the POST response body into the void
	let _ = std::io::copy(&mut resp.into_reader(), &mut std::io::sink());
```

My problem is that I can't see the progress of send_bytes as it's blocking, for download I can create a `reader` and then `.take(x)` from it as I wish

Is there any way to implement similar behavior for uploading?

**Comment by algesten** [comment]
Hey!

Check out [Request::send](https://docs.rs/ureq/2.5.0/ureq/struct.Request.html#method.send)

You can implement `Read` trait to gradually provide the bytes and do a progress meter.

**Comment by 12932** [comment]
> Hey!
> 
> Check out [Request::send](https://docs.rs/ureq/2.5.0/ureq/struct.Request.html#method.send)
> 
> You can implement `Read` trait to gradually provide the bytes and do a progress meter.

Thank you! that worked nicely, sorry for this 'dumb' issue

**Comment by orhun** [comment]
Hello @12932, can you provide an example of how you achieved this?

**Comment by orhun** [comment]
Also cc @algesten it would be nice to see an example.

**Comment by jsha** [comment]
@orhun a very rough sketch (I haven't tested this):

```rust
struct ProgressReader<R: Read> {
  inner: R,
  count: usize,
  total: usize,
};

impl Read for ProgressReader {
      fn read(&mut self, buf: &mut [u8]) -> Result<usize> {
          self.count += self.inner.read(buf)?;
          eprint!("\rsent {self.count} bytes of {self.total} total ({} %)", self.count / self.total);
      }
}

fn main() {
    let f = std::fs::File::open("example.file");
    let total = f.metadata().unwrap().len();
    let read = ProgressReader { inner: f, count: 0, total };
    let resp = ureq::post("http://httpbin.org/post")
        .send(read)?;
}
```

**Comment by orhun** [comment]
That's awesome, didn't know that I can use `Read` like that! Thanks @jsha 🐻

In case someone is interested, I implemented a progress bar for upload in https://github.com/orhun/rustypaste-cli/commit/1fe97a08431a99b63dbef95b6b3f02e2c7a7295e

**Comment by ytimenkov** [comment]
The suggested solution probably works for this case, when you need to report progress and have complete data to send, but I don't see how to repurpose it when I don't really have complete source to send. (On a side note, the snippet won't have proper `Content-Length` header and fall back to chunked encoding).

In my case I want to send zipped data into stream, but it obviously requires `Write`, so it feels naturally to turn `RequestBuilder` into `Write`, give it to `ZipWriter` and then get back and read the response. At least this is how everything else I've seen so far composes.

Starting a thread / process to just pipe data feels like overkill.

**Comment by ytimenkov** [comment]
> Have you seen an HTTP client in Rust that enables sending the body via a Write trait

No, that's what surprised me! (And not that I found many libraries at all...)

> I'm interested in inspiration of how one would go about implementing such a thing.

I was thinking about making a quick prototype, to see if it's possible, but had no time with job and life :(

Rough idea is to split `call_run` into 2 parts and return an `impl Write` which holds `Call<SendBodyState>` from the first one. Basically then it's up to the caller to drive sending body, like `send_body` does (actually `send_body` could be just `std::io::copy`, since the current `SendBody` can be turned into a reader). Once body is sent this `impl Write` can be converted into something which holds `Call<RecvResponse>` and basically the second part of `call_run` continues.

```rust
    let body_writer = ureq::put(upload_url).into_body_writer()?;
    let mut zip = ZipWriter::new(body_writer); // Gives ureq body writer to zip
    ...
    let body_writer = zip.finish()?; // Gets ureq body writer back
    let response = body_writer.into_response()?;
```

You obviously can't handle redirects this way, but 307/308 are a fatal errors in ureq for POST/PUT.

`Content-Length` vs chunked encoding can be handled similarly to how it's done now - if size is known, it could be added via header / special method on `RequestBuilder` (with same checks for whether exact number of bytes was sent before converting to response), otherwise chunked is more natural choice.

I can still try to do it, but not in next few weeks.
