### ISSUE TITLE
Low speed limit

### ISSUE THREAD

**Issue by gtklocker** [algesten/ureq#615]
I would like to implement something similar to curl's [low speed limit](https://daniel.haxx.se/blog/2020/05/11/curl-ootw-y-speed-limit/) ([also available through libcurl](https://curl.se/libcurl/c/CURLOPT_LOW_SPEED_LIMIT.html)).

My initial intuition was to wrap the `Read` returned from `Response::into_reader`, and keep track of the rate of transfer by detecting when ureq's `read` invocation returns `Ok(_)`. However I noticed that `read` invocations to the ureq's `Read` will block until an `Ok(_)` or fatal error is returned, and will not return `Interrupted` or `WouldBlock`. Looking into ureq's source this makes sense as the code mostly assumes a blocking socket (with one exception - for detecting if the server closed a stream).

Unfortunately I cannot make use of `timeout_read` as this affects also reads from the socket for when ureq is reading the headers, and a timeout to ureq at that stage would constitute an error before could I even get access to the reader.

I was wondering if I'm missing any alternative approach for implementing this. Is the blocking socket a hard requirement for ureq for some reason?

**Comment by algesten** [comment]
Since Rust is sync (and therefore "largely" single threaded), I think the most straight forward option for this kind of feature would be, as you say, to use a non-blocking socket and thread sleep between attempts to read.

If we had async IO we could of course use epoll to register a callback for incoming data (or even uring). This could in theory be done without going all the way to having async/await and an async runtime by using the (mio crate)[https://crates.io/crates/mio] directly (which underpins tokio and async-std). Using mio is (for good reasons) quite hairy, and I don't think we want this complication in ureq, but obviously I don't know how hairy until we see/try it.
