### ISSUE TITLE
`impl From<http::request::Parts> for ureq::Request`

### ISSUE THREAD

**Issue by Nemo157** [algesten/ureq#656]
Currently, it is possible to use libraries that expose requests as `http::request::Builder` and convert these for use by `ureq`; but if a library exposes an `http::Request` with a body there's no way to deconstruct that back into a `Builder` and send it with `ureq`. The closest option is to use `http::Request::into_parts` which separates out the `Parts` (which is what `Builder` holds internally) and the `Body`. If converting the `Parts` into a `ureq::Request` was supported then users could do something like:

```rust
fn do_request(req: http::Request) -> ureq::Response {
  let (parts, body) = req.into_parts();
  ureq::Request::from(parts).send(body)
}
```

It should also be possible to add this impl without any code duplication, move the existing code into this new impl then use `builder.body(()).into_parts().0.into()` to convert an `http::request::Builder` into an `http::request::Parts` to then convert to `ureq::Request`.

**Comment by Nemo157** [comment]
Hmmm, actually, it may require some duplication because of the current behavior with invalid `http::request::Builder`'s, I'd suggest in a future version switching to `impl TryFrom<http::request::Builder> for ureq::Request` and make invalid builders just return their error.

**Comment by MarijnS95** [comment]
@Nemo157 I was just in need of this too for the `oauth2` crate, and it was trivial enough to provide this implementation: #669

I came to the same conclusion that `http::request::Builder` should really have been implemented using `TryFrom`, instead of falsely providing some random default method/address for an _errored_ `Builder` that does not provide any sensible values (because it is storing an `Err`!).
