### ISSUE TITLE
Update requirement of `url=2.3.1`

### ISSUE THREAD

**Issue by jeffrey-dot-li** [algesten/ureq#720]
Are we able to update the dependency of `url=2.31.`? This is to make the crate compatible with other crate requiring a later `url` version (gcloud-sdk in my case needs `url>=2.5.0`. I read in the Cargo.toml that it is because of the cookie_store dependency, but updating `url` to 2.5.0 works on my fork and all tests pass. https://github.com/jeffrey-dot-li/ureq

**Comment by algesten** [comment]
Hi @jeffrey-dot-li, welcome to ureq!

Doing so is not possible at the moment. See comment here: https://github.com/algesten/ureq/blob/main/Cargo.toml#L44-L47

We would get double versions of the `idna` dep, and we use `cargo deny` to disallow multiple versions of the same dependency. I haven't investigated if `cookie-store` has an open issue for this.

**Comment by mohe2015** [comment]
In my opinion dependencies shouldn't be pinned unless absolutely necessary because they have the potential to break lots of downstream consumers and I also can't update some dependencies because of this.

Couldn't you loosen the restriction but still keep using that version in Cargo.lock and `cargo deny` would still be fine with that. Otherwise I think adding an exception to your deny config would be a better short term approach.

**Comment by edmorley** [comment]
A new version of `cookie_store` has been released which resolves the duplicate deps.

I've opened #722 to update to it, plus bump the matching deps.
