### ISSUE TITLE
Maintain a changelog of some sort

### ISSUE THREAD

**Issue by MCOfficer** [algesten/ureq#93]
*Disclaimer: this is a nitpick.*

Since ureq seems to get a new update about every week, every week i get a ping from dependabot. Updating is no big deal, but the lack of a changelog makes it **a bit** less convenient, since i have to check the commits to see what changed.

It would be more convenient to either have a maintained CHANGELOG.md or just some short bullet points on the tags.

**Comment by algesten** [comment]
Fair point!

@jsha you got any thoughts? I guess we'd just start it now. Have an "unreleased" section that we add to as/when we build out more things.

**Comment by jsha** [comment]
Yep, I think maintaining a changelog is a good idea. I think the lowest-overhead way to do this on a small project is, rather than maintaining an "unreleased" section, just go over the git logs since the last release and summarize at release time. So when we bump the version, the version-bump commit would also add a summary of changes to the changelog (and maybe copy that summary into either the commit description, or the subsequent tag, or both).

**Comment by MCOfficer** [comment]
Personally, i just use the release description whenever i tag a new one. As user, that's also the first place i'd look.

**Comment by algesten** [comment]
@MCOfficer You mean the github releases feature? Personally I'm ambivalent about that one since it's tied to github and would not move with the source repo if we ever migrate. Microsoft is behaving currently, but I'm not sure I'm ready to trust them just yet :)

**Comment by algesten** [comment]
This is happening since 1.4.0 in `CHANGELOG.md`
