### ISSUE TITLE
response: combine header fields with the same field name

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#95]
https://tools.ietf.org/html/rfc7230#section-3.2.2
>  A recipient MAY combine multiple header fields with the same field
   name into one "field-name: field-value" pair, without changing the
   semantics of the message, by appending each subsequent field value to
   the combined field value in order, separated by a comma.
> Note: In practice, the "Set-Cookie" header field ([RFC6265]) often
      appears multiple times in a response message and does not use the
      list syntax, violating the above requirements on multiple header
      fields with the same name.  Since it cannot be combined into a
      single field-value, recipients ought to handle "Set-Cookie" as a
      special case while processing header fields. 

Right now, response.header() only returns the value of the first header field with the requested name. It would be good to handle the case where there are repeats. Fortunately, the HTTP spec allows doing so by concatenation, which lets us preserve a nice simple API.

**Comment by algesten** [comment]
@jsha as an alternative, we could opt for retaining the current semantics of `header()`, that is returning _first value_, also for concatenated headers, and add a second:

```rust
    pub fn headers<'a>(&self, name: &'a str) -> &[&str] {
       ...
    }
```

This would return all values, concatenated or not. The advantage of that would be:

* Retain (clarify?) semantics for current `header`.
* Offload splitting/handling multiple values. This is otherwise pushed over to user of ureq to handle.

**Comment by jsha** [comment]
Actually, I hadn't noticed [Response.all](https://docs.rs/ureq/1.3.0/ureq/struct.Response.html#method.all), which has the semantics of returning all values for a given header field name. I think that fills the need well enough for now.

**Comment by algesten** [comment]
Oh. I forgot about that one :D
